# Basic Information
title: Yan Shao
position: Undergraduate Student
affiliation: Shanghai Jiao Tong University
affiliation_link: https://www.sjtu.edu.cn/
email: ryan_fox (at) sjtu.edu.cn

# Search Engine Optimization (SEO)
keywords: Yan Shao, Shanghai Jiao Tong University, machine learning, AI agent, efficient AI
description: Academic homepage of Yan Shao, an undergraduate student in Computer Science at Shanghai Jiao Tong University.
canonical: https://academic.ryanstarfox.top/

# Links
google_scholar: https://scholar.google.com/citations?user=mCnWy9UAAAAJ&hl=en
cv_link: /assets/files/curriculum_vitae.pdf
github_link: https://github.com/RyanStarFox
linkedin: https://www.linkedin.com/in/shaoyan0223/
blog_link: https://blog.ryanstarfox.top

# Images
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
